### PR TITLE
adds 105 protocol support for older clients

### PR DESCRIPTION
**Pull request by LordJoshie**
## PR Description
After updating to this latest repo, one of my regular players said they could no longer join. 
I compared the repo's and noticed the only change prohibiting the connection was the exclusion of the 105 protocol. I added it, and my player could then connect without issue. 

I also notice this repo allows connection without timeout, which is lovely. thanks !

## Have you tested it?
- [x ] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by erkam2002** [comment]
noooo

**Comment by Driesboy** [comment]
nope! the tecturepacks are broken then

**Comment by NFGamerMC** [comment]
Closed!

**Comment by LordJoshie** [comment]
welp.... sorry then. 
I tested this on my server, and it was working fine. don't think my player was using a texture pack tho.

**Pull request closed without merging**
